# Student Performance Data Handling and Analysis System

## Submitted By

**Name:** Kunal Srivastava

**Course:** B.Tech CSE (Data Science)

**College:** Maharana Pratap Engineering College

---

## Objective

To perform complete data handling, cleaning, transformation, analysis and report generation using the Pandas library.

In [6]:
import pandas as pd
import os

In [7]:
print(pd.__version__)

2.3.3

In [8]:
import pandas as pd
df  = pd.read_csv("../data/student_dataset_v2.csv")

In [9]:
df.head()

   ID       Name  StudyHours  Attendance  Marks
0   1  Student_1         4.4          96   59.5
1   2  Student_2         9.6          61   60.0
2   3  Student_3         7.6          65   80.2
3   4  Student_4         6.4          73   99.6
4   5  Student_5         2.4          68   79.7

In [10]:
df.tail()

       ID          Name  StudyHours  Attendance  Marks
995   996   Student_996         1.8          87   82.4
996   997   Student_997         9.3          57   43.8
997   998   Student_998         2.2          99   90.4
998   999   Student_999         9.6          52   40.2
999  1000  Student_1000         5.0          93   54.8

In [11]:
print("shape: ", df.shape)

shape:  (1000, 5)

In [12]:
print(df.columns)

Index(['ID', 'Name', 'StudyHours', 'Attendance', 'Marks'], dtype='object')

In [13]:
df.dtypes

ID              int64
Name           object
StudyHours    float64
Attendance      int64
Marks         float64
dtype: object

# Module 2: Data Inspection

In this module, we inspect the dataset to identify missing values, duplicate records, descriptive statistics, memory usage, and overall dataset information. This helps us understand the quality and structure of the data before cleaning.

In [14]:
df.isnull().sum()

ID             0
Name           0
StudyHours     0
Attendance     0
Marks         49
dtype: int64

In [15]:
df.duplicated().sum()

np.int64(0)

In [16]:
df.describe()

                ID   StudyHours   Attendance       Marks
count  1000.000000  1000.000000  1000.000000  951.000000
mean    500.500000     5.413500    75.122000   69.991377
std     288.819436     2.630701    14.692208   17.287756
min       1.000000     1.000000    50.000000   40.000000
25%     250.750000     3.100000    62.000000   55.600000
50%     500.500000     5.500000    75.000000   70.300000
75%     750.250000     7.700000    88.000000   85.100000
max    1000.000000    10.000000   100.000000   99.900000

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   ID          1000 non-null   int64
 1   Name        1000 non-null   object
 2   StudyHours  1000 non-null   float64
 3   Attendance  1000 non-null   int64
 4   Marks       951 non-null    float64
dtypes: float64(2), int64(2), object(1)
memory usage: 39.2+ KB

In [18]:
df.memory_usage(deep=True)

Index           132
ID             8000
Name          59893
StudyHours     8000
Attendance     8000
Marks          8000
dtype: int64

### Observation

- Checked for missing values.
- Checked for duplicate records.
- Displayed statistical summary of the dataset.
- Verified column data types.
- Examined memory usage.

# Module 3: Data Cleaning

In this module, the dataset is cleaned by removing duplicate records, handling missing values, validating the data, and preparing it for further analysis.

In [19]:
# Number of rows before removing duplicates
print("Rows before removing duplicates: ", len(df))

#Remove duplicate rows
df = df.drop_duplicates()

# Number of rows after removing duplicates
print("Rows after removing duplicates: ", len(df))

Rows before removing duplicates:  1000
Rows after removing duplicates:  1000

In [20]:
# Fill missing values

df = df.fillna({"StudyHours": df["StudyHours"].mean(),
               "Attendance": df["Attendance"].mean(),
               "Marks": df["Marks"].mean(),
               "Name":"Unknown"})

In [21]:
# Validating Attendance

df = df[(df["Attendance"] >= 0) & (df["Attendance"] <= 100)]

print(df["Attendance"].min())
print(df["Attendance"].max())

50
100

In [22]:
# Validating StudyHours 

df = df[df["StudyHours"] >= 0]
print(df["StudyHours"].min())

1.0

In [23]:
# Validating Marks 

df = df[(df["Marks"] >= 0) & (df["Marks"] <= 100)]

print(df["Marks"].min())
print(df["Marks"].max())

40.0
99.9

In [24]:
df.to_csv("../output/cleaned_data.csv", index = False)
print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

### Observation

- Duplicate records were removed.
- Missing values were handled.
- Attendance values were validated.
- Study hours were validated.
- Marks were validated.
- Cleaned dataset was exported successfully.

# Module 4: Data Transformation

In this module, new features are created from the existing dataset. These include Grade, Result, and Performance Score, which help in evaluating each student's overall performance.

In [25]:
def calculate_grade(marks):
    if marks >= 90:
        return "A"
    elif marks >= 75:
        return "B"
    elif marks >= 60:
        return "C"
    elif marks >= 40:
        return "D"
    else:
        return "F"
df["Grade"] = df["Marks"].apply(calculate_grade)

In [26]:
df[["Name", "Marks", "Grade"]].head()

        Name  Marks Grade
0  Student_1   59.5     D
1  Student_2   60.0     C
2  Student_3   80.2     B
3  Student_4   99.6     A
4  Student_5   79.7     B

In [27]:
df["Result"] = df["Marks"].apply( lambda x:"Pass" if x >= 40 else "Fail")

In [28]:
df[["Name", "Marks", "Result"]].head()

        Name  Marks Result
0  Student_1   59.5   Pass
1  Student_2   60.0   Pass
2  Student_3   80.2   Pass
3  Student_4   99.6   Pass
4  Student_5   79.7   Pass

In [29]:
#  Performance Score calculation

df["Performance Score"] = (df["Marks"] * 0.60 + df["Attendance"] * 0.25 + df["StudyHours"] * 2)

In [30]:
df.head()

,ID,Name,StudyHours,Attendance,Marks,Grade,Result,Performance Score
0,1,Student_1,4.4,96,59.5,D,Pass,68.50
1,2,Student_2,9.6,61,60.0,C,Pass,70.45
2,3,Student_3,7.6,65,80.2,B,Pass,79.57
3,4,Student_4,6.4,73,99.6,A,Pass,90.81
4,5,Student_5,2.4,68,79.7,B,Pass,69.62

In [31]:
df.to_csv("../output/cleaned_data.csv", index = False)
print("Dataset updated successfully!")

Dataset updated successfully!

### Observation

- Grade column was created based on marks.
- Result column identifies Pass or Fail.
- Performance Score combines Marks, Attendance, and Study Hours into a single score.
- Updated dataset was saved successfully.

# Module 5: Data Filtering

In this module, the dataset is filtered into different categories such as top-performing students, failed students, students with low attendance, and students who study more than 8 hours. Each filtered dataset is exported as a separate CSV file.

In [32]:
# Top performing students

toppers = df[df["Marks"] >= 90]
print("Number of toppers: ",len(toppers))
toppers.head()

Number of toppers:  149

,ID,Name,StudyHours,Attendance,Marks,Grade,Result,Performance Score
3,4,Student_4,6.4,73,99.6,A,Pass,90.81
10,11,Student_11,1.2,86,97.5,A,Pass,82.40
21,22,Student_22,2.3,94,95.6,A,Pass,85.46
25,26,Student_26,8.1,59,99.5,A,Pass,90.65
26,27,Student_27,2.8,65,95.6,A,Pass,79.21

In [34]:
toppers.to_csv("../output/toppers.csv", index = False)

In [35]:
# Failed students

failed_students = df[df['Result']  == 'Fail']
print("Number of failed students: ", len(failed_students))
failed_students.head(10)

Number of failed students:  0

Empty DataFrame
Columns: [ID, Name, StudyHours, Attendance, Marks, Grade, Result, Performance Score]
Index: []

In [36]:
failed_students.to_csv("../output/failed_students.csv", index = False)

In [38]:
# Attendance more than 75%

low_attendance = df[df["Attendance"] < 75]
print("Students with Attendance below 75% : ", len(low_attendance))
low_attendance.head(10)

Students with Attendance below 75% :  490

,ID,Name,StudyHours,Attendance,Marks,Grade,Result,Performance Score
1,2,Student_2,9.6,61,60.000000,C,Pass,70.450000
2,3,Student_3,7.6,65,80.200000,B,Pass,79.570000
3,4,Student_4,6.4,73,99.600000,A,Pass,90.810000
4,5,Student_5,2.4,68,79.700000,B,Pass,69.620000
5,6,Student_6,2.4,57,73.500000,C,Pass,63.150000
7,8,Student_8,8.8,70,67.900000,C,Pass,75.840000
8,9,Student_9,6.4,66,43.600000,D,Pass,55.460000
9,10,Student_10,7.4,72,73.700000,C,Pass,77.020000
11,12,Student_12,9.7,65,50.500000,D,Pass,65.950000
12,13,Student_13,8.5,55,69.991377,C,Pass,72.744826

In [39]:
low_attendance.to_csv("../output/low_attendance.csv", index = False)

In [40]:
# study hour more than 8

study_more_than_8 = df[df['StudyHours'] > 8]
print("Students studying more than 8 hours: ", len(study_more_than_8))
study_more_than_8.head(10)

Students studying more than 8 hours:  216

,ID,Name,StudyHours,Attendance,Marks,Grade,Result,Performance Score
1,2,Student_2,9.6,61,60.000000,C,Pass,70.450000
7,8,Student_8,8.8,70,67.900000,C,Pass,75.840000
11,12,Student_12,9.7,65,50.500000,D,Pass,65.950000
12,13,Student_13,8.5,55,69.991377,C,Pass,72.744826
25,26,Student_26,8.1,59,99.500000,A,Pass,90.650000
33,34,Student_34,9.5,56,47.700000,D,Pass,61.620000
34,35,Student_35,9.7,63,89.600000,B,Pass,88.910000
35,36,Student_36,8.3,64,86.900000,B,Pass,84.740000
43,44,Student_44,9.2,78,73.200000,C,Pass,81.820000
50,51,Student_51,9.7,91,69.800000,C,Pass,84.030000

In [41]:
study_more_than_8.to_csv("../output/study_more_than_8.csv", index = False)

In [42]:
# verification of output files

import os
print("Files generated in the output folder: ")

for file in os.listdir("../output"):
    print(file)

Files generated in the output folder:
cleaned_data.csv
failed_students.csv
low_attendance.csv
study_more_than_8.csv
toppers.csv

### Conclusion

The dataset was successfully filtered into different categories:

- Top-performing students (Marks ≥ 90)
- Failed students
- Students with attendance below 75%
- Students studying more than 8 hours

Each filtered dataset was exported as a separate CSV file for further analysis.

# Module 6: Data Analysis

## Objective

The objective of this module is to analyze the student dataset by calculating important performance metrics such as average marks, highest and lowest marks, attendance, study hours, pass percentage, fail percentage, and grade distribution.

In [43]:
# Calculate analysis metrics

average_marks = df["Marks"].mean()
highest_marks = df["Marks"].max()
lowest_marks = df["Marks"].min()

average_attendance = df["Attendance"].mean()
average_study_hours = df["StudyHours"].mean()

pass_percentage = (df["Result"] == "Pass").mean() * 100
fail_percentage = (df["Result"] == "Fail").mean() * 100

analysis_summary = pd.DataFrame({
    "Metric": [
        "Average Marks",
        "Highest Marks",
        "Lowest Marks",
        "Average Attendance (%)",
        "Average StudyHours",
        "Pass Percentage(%)",
        "Fail Percentage(%)"
    ],
    "Value": [
        round(average_marks, 2),
        highest_marks,
        lowest_marks,
        round(average_attendance, 2),
        round(average_study_hours, 2),
        round(pass_percentage, 2),
        round(fail_percentage, 2)
    ]
})

analysis_summary

                   Metric   Value
0           Average Marks   69.99
1           Highest Marks   99.90
2            Lowest Marks   40.00
3  Average Attendance (%)   75.12
4      Average StudyHours    5.41
5      Pass Percentage(%)  100.00
6      Fail Percentage(%)    0.00

In [44]:
grade_distribution = (
    df["Grade"]
    .value_counts()
    .reset_index()
)

grade_distribution.columns = ["Grade", "Number of Students"]

grade_distribution

  Grade  Number of Students
0     D                 310
1     C                 290
2     B                 251
3     A                 149

In [46]:
# Highest Scoring Student

highest_student = df.nlargest(
    1,
    "Marks"
)[["ID", "Name", "Marks", "Grade"]]

highest_student

      ID         Name  Marks Grade
341  342  Student_342   99.9     A

In [47]:
# Lowest Scoring Student

lowest_student = df.nsmallest(
    1,
    "Marks"
)[["ID", "Name", "Marks", "Grade"]]

lowest_student

      ID         Name  Marks Grade
991  992  Student_992   40.0     D

In [48]:
top10 = df.nlargest(
    10,
    "Performance Score"
)[["ID", "Name", "Marks",
   "Attendance",
   "StudyHours",
   "Performance Score"]]

top10

      ID         Name  Marks  Attendance  StudyHours  Performance Score
478  479  Student_479   97.9          91         9.7             100.89
252  253  Student_253   96.2         100         8.7             100.12
441  442  Student_442   91.0         100         9.9              99.40
241  242  Student_242   95.1          92         9.6              99.26
276  277  Student_277   99.5          90         8.2              98.60
731  732  Student_732   96.5          95         8.3              98.25
475  476  Student_476   89.3          99         9.9              98.13
114  115  Student_115   99.8          99         6.7              98.03
51    52   Student_52   99.5          88         8.0              97.70
414  415  Student_415   98.9          97         6.7              96.99

### Observation

- Calculated average, highest, and lowest marks.
- Computed average attendance and study hours.
- Calculated pass and fail percentages.
- Analyzed the distribution of grades.
- Identified the highest and lowest scoring students.
- Displayed the top 10 students based on Performance Score.

# Module 7: Sorting

## Objective

The dataset is sorted based on Marks, Attendance, and Study Hours to analyze student performance from different perspectives.

In [57]:
# Sort students by Marks (Highest to Lowest)

sorted_marks = df.sort_values(by="Marks", ascending=False)

sorted_marks[
    ["ID",
     "Name",
     "Marks",
     "Grade",
     "Performance Score"]
].head(10)

      ID         Name  Marks Grade  Performance Score
341  342  Student_342   99.9     A              91.54
114  115  Student_115   99.8     A              98.03
299  300  Student_300   99.8     A              76.73
102  103  Student_103   99.7     A              87.17
630  631  Student_631   99.7     A              89.37
847  848  Student_848   99.6     A              95.26
3      4    Student_4   99.6     A              90.81
701  702  Student_702   99.6     A              77.01
276  277  Student_277   99.5     A              98.60
51    52   Student_52   99.5     A              97.70

In [60]:
sorted_marks.to_csv("../output/sorted_by_marks.csv", index=False)

In [61]:
# Sort students by Attendance

sorted_attendance = df.sort_values(by="Attendance", ascending=False)

sorted_attendance[
    ["ID",
     "Name",
     "Attendance",
     "Marks"]
].head(10)

      ID         Name  Attendance  Marks
562  563  Student_563         100   90.2
331  332  Student_332         100   87.3
145  146  Student_146         100   46.6
38    39   Student_39         100   58.2
843  844  Student_844         100   66.6
520  521  Student_521         100   71.6
252  253  Student_253         100   96.2
528  529  Student_529         100   72.4
541  542  Student_542         100   46.0
441  442  Student_442         100   91.0

In [62]:
sorted_attendance.to_csv("../output/sorted_by_attendance.csv", index=False)

In [63]:
# Sort students by Study Hours

sorted_study_hours = df.sort_values(by="StudyHours", ascending=False)

sorted_study_hours[
    ["ID",
     "Name",
     "StudyHours",
     "Performance Score"]
].head(10)

      ID         Name  StudyHours  Performance Score
531  532  Student_532        10.0              74.73
532  533  Student_533        10.0              90.33
847  848  Student_848        10.0              95.26
932  933  Student_933         9.9              82.13
661  662  Student_662         9.9              93.75
705  706  Student_706         9.9              73.23
261  262  Student_262         9.9              90.20
390  391  Student_391         9.9              67.05
69    70   Student_70         9.9              91.40
475  476  Student_476         9.9              98.13

In [64]:
sorted_study_hours.to_csv("../output/sorted_by_study_hours.csv", index=False)

In [65]:
print("Sorting completed successfully!")

Sorting completed successfully!

### Observation

- Students were sorted according to marks.
- Students were sorted according to attendance.
- Students were sorted according to study hours.
- Separate CSV files were generated for future reference.

# Module 8: Grouping

## Objective

The objective of this module is to group students based on their grades and calculate important statistics such as average marks, number of students, and average attendance for each grade.

In [66]:
average_marks_by_grade = (
    df.groupby("Grade")["Marks"]
      .mean()
      .reset_index()
)

average_marks_by_grade.columns = ["Grade", "Average Marks"]

average_marks_by_grade

  Grade  Average Marks
0     A      95.003356
1     B      82.627888
2     C      67.930267
3     D      49.666129

In [67]:
students_per_grade = (
    df.groupby("Grade")
      .size()
      .reset_index(name="Number of Students")
)

students_per_grade

  Grade  Number of Students
0     A                 149
1     B                 251
2     C                 290
3     D                 310

In [68]:
average_attendance_by_grade = (
    df.groupby("Grade")["Attendance"]
      .mean()
      .reset_index()
)

average_attendance_by_grade.columns = [
    "Grade",
    "Average Attendance"
]

average_attendance_by_grade

  Grade  Average Attendance
0     A           76.073826
1     B           74.577689
2     C           75.434483
3     D           74.812903

In [69]:
grade_summary = (
    df.groupby("Grade")
      .agg(
          Average_Marks=("Marks", "mean"),
          Average_Attendance=("Attendance", "mean"),
          Student_Count=("Grade", "count")
      )
      .reset_index()
)

grade_summary

  Grade  Average_Marks  Average_Attendance  Student_Count
0     A      95.003356           76.073826            149
1     B      82.627888           74.577689            251
2     C      67.930267           75.434483            290
3     D      49.666129           74.812903            310

In [70]:
grade_summary.to_csv("../output/grade_summary.csv", index=False)

print("Grade summary saved successfully!")

Grade summary saved successfully!

### Observation

- Students were grouped according to their grades.
- Average marks were calculated for each grade.
- Average attendance was calculated for each grade.
- Number of students in each grade was determined.
- Grade summary was exported successfully.

# Module 9: Statistical Analysis

## Objective

The objective of this module is to perform statistical analysis on the student dataset by calculating measures such as mean, median, mode, standard deviation, variance, and correlation between numerical attributes.

In [71]:
mean_values = df[["StudyHours", "Attendance", "Marks", "Performance Score"]].mean()

print("Mean Values:")
mean_values

Mean Values:

StudyHours            5.413500
Attendance           75.122000
Marks                69.991377
Performance Score    71.602326
dtype: float64

In [72]:
median_values = df[["StudyHours", "Attendance", "Marks", "Performance Score"]].median()

print("Median Values:")
median_values

Median Values:

StudyHours            5.500000
Attendance           75.000000
Marks                69.991377
Performance Score    72.155000
dtype: float64

In [73]:
mode_values = df[["StudyHours", "Attendance", "Marks"]].mode()

print("Mode Values:")
mode_values

Mode Values:

   StudyHours  Attendance      Marks
0         9.1          64  69.991377

In [74]:
std_values = df[["StudyHours", "Attendance", "Marks", "Performance Score"]].std()

print("Standard Deviation:")
std_values

Standard Deviation:

StudyHours            2.630701
Attendance           14.692208
Marks                16.858451
Performance Score    12.215717
dtype: float64

In [75]:
variance_values = df[["StudyHours", "Attendance", "Marks", "Performance Score"]].var()

print("Variance:")
variance_values

Variance:

StudyHours             6.920588
Attendance           215.860977
Marks                284.207377
Performance Score    149.223746
dtype: float64

In [76]:
correlation_matrix = df[
    ["StudyHours", "Attendance", "Marks", "Performance Score"]
].corr()

correlation_matrix

                   StudyHours  Attendance     Marks  Performance Score
StudyHours           1.000000    0.033247  0.021274           0.458320
Attendance           0.033247    1.000000  0.029419           0.339362
Marks                0.021274    0.029419  1.000000           0.846046
Performance Score    0.458320    0.339362  0.846046           1.000000

In [77]:
correlation_matrix.to_csv("../output/correlation_matrix.csv")

print("Correlation matrix saved successfully!")

Correlation matrix saved successfully!

### Observation

- Calculated mean, median, and mode.
- Computed standard deviation and variance.
- Analyzed correlations among numerical features.
- Visualized the correlation matrix.
- Exported the correlation matrix as a CSV file.

# Module 10: Report Generation

## Objective

The objective of this module is to generate a final summary report containing key statistics of the student dataset. The report includes total students, pass/fail counts, highest and lowest marks, average marks, average attendance, and grade-wise distribution.

In [78]:
# Total Students
total_students = len(df)

# Passed Students
passed_students = len(df[df["Result"] == "Pass"])

# Failed Students
failed_students = len(df[df["Result"] == "Fail"])

# Highest Marks
highest_marks = df["Marks"].max()

# Lowest Marks
lowest_marks = df["Marks"].min()

# Average Marks
average_marks = round(df["Marks"].mean(), 2)

# Average Attendance
average_attendance = round(df["Attendance"].mean(), 2)

print("Calculations completed successfully!")

Calculations completed successfully!

In [79]:
grade_distribution = df["Grade"].value_counts()

grade_distribution

Grade
D    310
C    290
B    251
A    149
Name: count, dtype: int64

In [80]:
report = pd.DataFrame({
    "Metric": [
        "Total Students",
        "Passed Students",
        "Failed Students",
        "Highest Marks",
        "Lowest Marks",
        "Average Marks",
        "Average Attendance (%)"
    ],
    "Value": [
        total_students,
        passed_students,
        failed_students,
        highest_marks,
        lowest_marks,
        average_marks,
        average_attendance
    ]
})

report

                   Metric    Value
0          Total Students  1000.00
1         Passed Students  1000.00
2         Failed Students     0.00
3           Highest Marks    99.90
4            Lowest Marks    40.00
5           Average Marks    69.99
6  Average Attendance (%)    75.12

In [81]:
for grade, count in grade_distribution.items():
    report.loc[len(report)] = [f"Grade {grade}", count]

report

                    Metric    Value
0           Total Students  1000.00
1          Passed Students  1000.00
2          Failed Students     0.00
3            Highest Marks    99.90
4             Lowest Marks    40.00
5            Average Marks    69.99
6   Average Attendance (%)    75.12
7                  Grade D   310.00
8                  Grade C   290.00
9                  Grade B   251.00
10                 Grade A   149.00

In [82]:
report.to_csv("../output/report.csv", index=False)

print("Report generated successfully!")

Report generated successfully!

In [85]:
 # VERIFY
report

                    Metric    Value
0           Total Students  1000.00
1          Passed Students  1000.00
2          Failed Students     0.00
3            Highest Marks    99.90
4             Lowest Marks    40.00
5            Average Marks    69.99
6   Average Attendance (%)    75.12
7                  Grade D   310.00
8                  Grade C   290.00
9                  Grade B   251.00
10                 Grade A   149.00

### Observation

- Generated the final project report.
- Included overall student statistics.
- Included grade-wise distribution.
- Exported the report as **report.csv**.

In [86]:
import os

output_path = "../output"

print("Generated Files:")
print("-" * 30)

for file in sorted(os.listdir(output_path)):
    print(file)

Generated Files:
------------------------------
cleaned_data.csv
correlation_matrix.csv
failed_students.csv
grade_summary.csv
low_attendance.csv
report.csv
sorted_by_attendance.csv
sorted_by_marks.csv
sorted_by_study_hours.csv
study_more_than_8.csv
toppers.csv

In [87]:
df.head()

,ID,Name,StudyHours,Attendance,Marks,Grade,Result,Performance Score
0,1,Student_1,4.4,96,59.5,D,Pass,68.50
1,2,Student_2,9.6,61,60.0,C,Pass,70.45
2,3,Student_3,7.6,65,80.2,B,Pass,79.57
3,4,Student_4,6.4,73,99.6,A,Pass,90.81
4,5,Student_5,2.4,68,79.7,B,Pass,69.62

# Project Completed ✅

## Summary

This project successfully demonstrates the complete data analysis lifecycle using the Pandas library.

### Modules Completed

- Data Loading
- Data Inspection
- Data Cleaning
- Data Transformation
- Data Filtering
- Data Analysis
- Sorting
- Grouping
- Statistical Analysis
- Report Generation
- Data Export

### Technologies Used

- Python
- Pandas
- Jupyter Notebook
  

### Output Files Generated

- cleaned_data.csv
- toppers.csv
- failed_students.csv
- low_attendance.csv
- study_more_than_8.csv
- grade_summary.csv
- correlation_matrix.csv
- report.csv

This project demonstrates practical data preprocessing, transformation, statistical analysis, and report generation using Python.